### PR TITLE
Add a travis configuration, setup like the rest of the drupal repos.

### PR DESCRIPTION
**Pull request by jonathangreen**
part of: 
https://github.com/Islandora-CLAW/CLAW/issues/540

blocked by:
https://github.com/Islandora-CLAW/CLAW/issues/542

### CODE REVIEW

**Comment by DiegoPino** [comment]
@jonathangreen I would not say blocked. I would even prefer if your, this, pull request would be merged first. So consequent commits to #5 could be tested reliably. 😁

**Comment by jonathangreen** [comment]
That makes sense @DiegoPino. Someone in the organization needs to turn on travis for the repo as well.

**Comment by DiegoPino** [comment]
@jonathangreen so lets give it a test drive!

**Comment by jonathangreen** [comment]
There we go. I pushed a rebased commit and it looks like travis is spinning up.

**Comment by DiegoPino** [comment]
@jonathangreen looks fine, thanks! Need oneOf(@dannylamb,@whikloj,@ruebot) 's blessing here to merge, since we need to merge with test his failing, it's the only way.

**Comment by whikloj** [comment]
I'll merge, and then remove the old HAL tests and @DiegoPino is writing new ones.

**Pull request merged**
